name: Blockchain Node Test

on: [push, pull_request]

jobs:
  test-blockchain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start blockchain nodes with Docker Compose
        run: |
          docker-compose up --build -d
          sleep 5  # Wait for the nodes to start

      - name: Check logs for mined block
        run: |
          sleep 5  # Allow time for block mining
          docker logs node1 > node1.log
          docker logs node2 > node2.log

          echo "Node1 Logs:"
          cat node1.log

          echo "Node2 Logs:"
          cat node2.log

          if grep -q "New block mined" node1.log && grep -q "New block mined" node2.log; then
            echo "✅ Blockchain test passed!"
            exit 0
          else
            echo "❌ Blockchain test failed!"
            exit 1
          fi
